name: build-macosx

on:
  push:
    branches:
      - 'master'

jobs:
  amd64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1
      -
        name: Setup environment
        run: |
          chmod +x scripts/install_macos_dependencies.sh
          ./scripts/install_macos_dependencies.sh
      -
        name: Build
        run: |
          chmod +x compile_macosx.sh
          ./compile_macosx.sh amd64 Release
      -
        name: Export artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macosx-amd64.tar.gz
          path: out/binary_distrib.tar.gz
  arm64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1
      -
        name: Setup environment
        run: |
          chmod +x scripts/install_macos_dependencies.sh
          ./scripts/install_macos_dependencies.sh
      -
        name: Build
        run: |
          chmod +x compile_macosx.sh
          ./compile_macosx.sh arm64 Release
      -
        name: Export artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macosx-arm64.tar.gz
          path: out/binary_distrib.tar.gz

