name: build-linux

on:
  push:
    branches:
      - 'master'

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        run: |
          chmod +x compile_linux.sh
          ./compile_linux.sh amd64
      -
        name: Visualize output
        run: |
          ls -a
      -
        name: Export artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-amd64.zip
          path: |
            out/binary_distrib.tar.gz
